---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat-db
  namespace: rocket-chat
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: rocketchat-db
