---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: snow-create-change-record
  labels:
    app.kubernetes.io/name: rocketchat
spec:
  tower_auth_secret: admin-playback-token
  workflow_template_name: snow-create-change-record
  extra_vars:
    msg: "Hello!"
